// ─────────────────────────────────────────
//  generators/docxGenerator.js
//  Creates a formatted Word (.docx) document
// ─────────────────────────────────────────
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, Table, TableRow, TableCell, WidthType, ShadingType } = require('docx');
const fs = require('fs');
const path = require('path');

const OUTPUT_DIR = process.env.OUTPUT_DIR || './outputs';

async function generateDOCX(query, answer, chunks, timestamp) {
  const filename = `report_${timestamp}.docx`;
  const filePath = path.join(OUTPUT_DIR, filename);

  const sources = [...new Set(chunks.map(c => c.metadata?.filename))];
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Build answer paragraphs (split by newlines)
  const answerParagraphs = answer.split('\n')
    .filter(line => line.trim())
    .map(line => new Paragraph({
      children: [new TextRun({ text: line, size: 24 })],
      spacing: { after: 120 },
    }));

  // Build sources list
  const sourceParagraphs = sources.map((src, i) =>
    new Paragraph({
      children: [new TextRun({ text: `${i + 1}. ${src}`, size: 22 })],
      spacing: { after: 80 },
    })
  );

  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        // ── Title ─────────────────────────────
        new Paragraph({
          text: 'Business Document Report',
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 },
        }),

        // ── Date ─────────────────────────────
        new Paragraph({
          children: [
            new TextRun({ text: `Generated: ${date}`, color: '888888', italics: true, size: 20 }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),

        // ── Query Section ─────────────────────
        new Paragraph({
          text: '📋 Query',
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 120 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: query, size: 24, italics: true, color: '1a73e8' }),
          ],
          spacing: { after: 400 },
        }),

        // ── Answer Section ────────────────────
        new Paragraph({
          text: '🤖 Answer',
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 120 },
        }),
        ...answerParagraphs,

        // ── Sources Section ───────────────────
        new Paragraph({
          text: '📂 Sources Referenced',
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 400, after: 120 },
        }),
        ...sourceParagraphs,

        // ── Footer note ───────────────────────
        new Paragraph({
          children: [
            new TextRun({
              text: 'Generated by WhatsApp Business Document Assistant',
              size: 18,
              color: 'AAAAAA',
              italics: true,
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { before: 600 },
        }),
      ],
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(filePath, buffer);

  console.log(`📝 DOCX generated: ${filePath}`);
  return filePath;
}

module.exports = { generateDOCX };
