// src/generators/imageGenerator.js
// Uses sharp instead of canvas — much lighter on memory
const sharp = require('sharp');
const path = require('path');
const logger = require('../utils/logger');

const OUTPUT_DIR = process.env.OUTPUT_DIR || './outputs';

async function generateImage(query, answer, timestamp) {
  const filename = `summary_${timestamp}.jpg`;
  const filePath = path.join(OUTPUT_DIR, filename);

  const date = new Date().toLocaleDateString();

  // Truncate text to fit
  const shortQuery  = query.length > 80  ? query.substring(0, 77) + '...'  : query;
  const shortAnswer = answer.length > 300 ? answer.substring(0, 297) + '...' : answer;

  // Build SVG — no canvas needed, pure text
  const svg = `
<svg width="800" height="500" xmlns="http://www.w3.org/2000/svg">

  <!-- Background -->
  <rect width="800" height="500" fill="#FFFFFF"/>

  <!-- Header bar -->
  <rect width="800" height="70" fill="#1a73e8"/>
  <text x="400" y="42" font-family="Arial" font-size="22"
        font-weight="bold" fill="white" text-anchor="middle">
    Business Document Assistant
  </text>
  <text x="750" y="58" font-family="Arial" font-size="12"
        fill="rgba(255,255,255,0.8)" text-anchor="end">
    ${date}
  </text>

  <!-- Query box -->
  <rect x="30" y="90" width="740" height="70" rx="8" fill="#EFF8FF"/>
  <text x="50" y="115" font-family="Arial" font-size="13"
        font-weight="bold" fill="#1a73e8">
    QUERY
  </text>
  <text x="50" y="140" font-family="Arial" font-size="13" fill="#333333">
    ${escapeXml(shortQuery)}
  </text>

  <!-- Answer box -->
  <rect x="30" y="175" width="740" height="280" rx="8" fill="#F8F9FA"/>
  <text x="50" y="202" font-family="Arial" font-size="13"
        font-weight="bold" fill="#1a73e8">
    ANSWER
  </text>
  ${wrapTextSVG(shortAnswer, 50, 225, 720, 18)}

  <!-- Footer -->
  <rect y="460" width="800" height="40" fill="#F0F0F0"/>
  <text x="400" y="484" font-family="Arial" font-size="11"
        fill="#888888" text-anchor="middle">
    Generated by WhatsApp Business Document Assistant
  </text>

</svg>`;

  // Convert SVG to JPG using sharp
  await sharp(Buffer.from(svg))
    .jpeg({ quality: 90 })
    .toFile(filePath);

  logger.success(`Image generated: ${filePath}`);
  return filePath;
}

// Wrap long text into SVG tspan lines
function wrapTextSVG(text, x, y, maxWidth, lineHeight) {
  const words = text.split(' ');
  const lines = [];
  let current = '';
  const charsPerLine = Math.floor(maxWidth / 8);

  words.forEach(word => {
    if ((current + word).length > charsPerLine) {
      lines.push(current.trim());
      current = word + ' ';
    } else {
      current += word + ' ';
    }
  });
  if (current.trim()) lines.push(current.trim());

  return lines.slice(0, 13).map((line, i) =>
    `<text x="${x}" y="${y + i * lineHeight}"
      font-family="Arial" font-size="12" fill="#333333">
      ${escapeXml(line)}
    </text>`
  ).join('\n');
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

module.exports = { generateImage };