// ─────────────────────────────────────────
//  src/generators/pdfGenerator.js
//  College-branded PDF report generator
//  Uses pdfkit
// ─────────────────────────────────────────
const PDFDocument = require('pdfkit');
const fs = require('fs-extra');
const path = require('path');
const logger = require('../utils/logger');
const { getDeptName } = require('../utils/deptMapper');

const OUTPUT_DIR = process.env.OUTPUT_DIR || './outputs';
const COLLEGE_NAME = process.env.COLLEGE_NAME || 'College of Engineering';
const COLLEGE_CODE = process.env.COLLEGE_CODE || 'CE';

// ── Color palette ─────────────────────────
const COLORS = {
   primary: '#1a237e', // Deep blue
   secondary: '#283593',
   accent: '#e53935', // Red for warnings
   success: '#2e7d32',
   text: '#212121',
   subtext: '#616161',
   border: '#e0e0e0',
   lightBg: '#f5f5f5',
};

// ── Draw page header ──────────────────────
function drawHeader(doc, dept) {
   const deptName = dept ? getDeptName(dept) : 'All Departments';
   const generatedDate = new Date().toLocaleDateString('en-IN', {
      day: '2-digit', month: 'long', year: 'numeric',
   });

   // Title bar background
   doc.rect(0, 0, doc.page.width, 80).fill(COLORS.primary);

   // College name
   doc.font('Helvetica-Bold').fontSize(16).fillColor('#FFFFFF')
      .text(COLLEGE_NAME, 40, 18, { align: 'left' });

   // College code badge
   doc.font('Helvetica-Bold').fontSize(11).fillColor('#FFD54F')
      .text(COLLEGE_CODE, doc.page.width - 90, 20, { align: 'right' });

   // Sub-header: dept + date
   doc.font('Helvetica').fontSize(10).fillColor('#B3C5E0')
      .text(`Department: ${deptName}  |  Generated: ${generatedDate}`, 40, 45, { align: 'left' });

   // Divider line
   doc.rect(0, 80, doc.page.width, 3).fill(COLORS.accent);

   doc.y = 100;
   doc.fillColor(COLORS.text);
}

// ── Draw section heading ──────────────────
function drawSectionHeading(doc, title) {
   doc.moveDown(0.5);
   doc.rect(40, doc.y, doc.page.width - 80, 22).fill(COLORS.secondary);
   doc.font('Helvetica-Bold').fontSize(11).fillColor('#FFFFFF')
      .text(title, 48, doc.y - 18);
   doc.y += 8;
   doc.fillColor(COLORS.text);
   doc.moveDown(0.3);
}

// ── Draw a key-value info box ─────────────
function drawInfoBox(doc, pairs) {
   let startY = doc.y;
   doc.rect(40, startY, doc.page.width - 80, pairs.length * 20 + 10).fill(COLORS.lightBg);

   pairs.forEach(([key, val], i) => {
      const y = startY + 8 + i * 20;
      doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.subtext).text(key + ':', 50, y, { continued: true });
      doc.font('Helvetica').fontSize(9).fillColor(COLORS.text).text('  ' + val);
   });

   doc.y = startY + pairs.length * 20 + 18;
}

// ── Draw page footer ──────────────────────
function drawFooter(doc) {
   const bottom = doc.page.height - 40;
   doc.rect(0, bottom - 3, doc.page.width, 43).fill(COLORS.primary);
   doc.font('Helvetica').fontSize(8).fillColor('#B3C5E0')
      .text(
         `${COLLEGE_NAME}  |  Confidential — For internal use only  |  Page ${doc.bufferedPageRange().count}`,
         40, bottom + 8
      );
}

// ── Generate a department report PDF ──────
async function generateDeptReportPDF(reportText, dept, meta = {}) {
   const filename = `dept_report_${dept}_${Date.now()}.pdf`;
   const filePath = path.join(OUTPUT_DIR, filename);
   await fs.ensureDir(OUTPUT_DIR);

   return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const out = fs.createWriteStream(filePath);
      doc.pipe(out);

      drawHeader(doc, dept);

      // Report title
      doc.font('Helvetica-Bold').fontSize(18).fillColor(COLORS.primary)
         .text(`${dept} Department Report`, 40, doc.y, { align: 'center' });
      doc.moveDown(0.5);

      // Meta info box
      if (meta.uploadedBy || meta.studentCount) {
         drawInfoBox(doc, [
            ['Uploaded By', meta.uploadedBy || 'N/A'],
            ['Total Students', meta.studentCount || 'N/A'],
            ['Last Upload', meta.lastUpload ? new Date(meta.lastUpload).toLocaleDateString('en-IN') : 'N/A'],
            ['Generated By', meta.requestedBy || 'N/A'],
         ]);
      }

      doc.moveDown(0.5);
      drawSectionHeading(doc, 'REPORT DETAILS');

      // Report body — handle section headings and normal text
      const lines = reportText.split('\n');
      lines.forEach(line => {
         if (doc.y > doc.page.height - 80) {
            doc.addPage();
            drawHeader(doc, dept);
         }

         const trimmed = line.trim();
         if (!trimmed) { doc.moveDown(0.3); return; }

         // Section headings (numbered or all-caps)
         if (/^\d+\./.test(trimmed) || /^[A-Z\s]{4,}:?$/.test(trimmed)) {
            doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.primary).text(trimmed, 40, doc.y);
         } else if (trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*')) {
            doc.font('Helvetica').fontSize(9).fillColor(COLORS.text)
               .text(trimmed, 55, doc.y, { width: doc.page.width - 95 });
         } else if (trimmed.includes('⚠️') || trimmed.toLowerCase().includes('at-risk') || trimmed.toLowerCase().includes('below 75')) {
            doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.accent)
               .text(trimmed, 40, doc.y, { width: doc.page.width - 80 });
         } else {
            doc.font('Helvetica').fontSize(9).fillColor(COLORS.text)
               .text(trimmed, 40, doc.y, { width: doc.page.width - 80 });
         }
      });

      drawFooter(doc);
      doc.end();

      out.on('finish', () => {
         logger.success(`PDF report generated: ${filename}`);
         resolve(filePath);
      });
      out.on('error', reject);
   });
}

// ── Generate a student profile PDF ────────
async function generateStudentProfilePDF(answer, query, meta = {}) {
   const filename = `student_profile_${Date.now()}.pdf`;
   const filePath = path.join(OUTPUT_DIR, filename);
   await fs.ensureDir(OUTPUT_DIR);

   return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const out = fs.createWriteStream(filePath);
      doc.pipe(out);

      drawHeader(doc, meta.dept || '');

      doc.font('Helvetica-Bold').fontSize(16).fillColor(COLORS.primary)
         .text('Student Profile', 40, doc.y, { align: 'center' });
      doc.moveDown(0.3);

      doc.font('Helvetica').fontSize(10).fillColor(COLORS.subtext)
         .text(`Query: "${query}"`, 40, doc.y, { align: 'center' });
      doc.moveDown(1);

      drawSectionHeading(doc, 'STUDENT INFORMATION');

      const lines = answer.split('\n');
      lines.forEach(line => {
         const trimmed = line.trim();
         if (!trimmed) { doc.moveDown(0.3); return; }
         if (trimmed.includes('⚠️') || trimmed.includes('AT-RISK')) {
            doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.accent).text(trimmed, 40, doc.y, { width: doc.page.width - 80 });
         } else if (/^[A-Z][\w\s]+:/.test(trimmed)) {
            // Bold label: value lines
            const colonIdx = trimmed.indexOf(':');
            const label = trimmed.slice(0, colonIdx + 1);
            const value = trimmed.slice(colonIdx + 1);
            doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.text)
               .text(label, 40, doc.y, { continued: true });
            doc.font('Helvetica').fontSize(10).fillColor(COLORS.text).text(value);
         } else {
            doc.font('Helvetica').fontSize(10).fillColor(COLORS.text)
               .text(trimmed, 40, doc.y, { width: doc.page.width - 80 });
         }
      });

      drawFooter(doc);
      doc.end();

      out.on('finish', () => {
         logger.success(`Student profile PDF generated: ${filename}`);
         resolve(filePath);
      });
      out.on('error', reject);
   });
}

// ── Legacy generic PDF ────────────────────
async function generatePDF(query, answer, chunks, timestamp) {
   return generateStudentProfilePDF(answer, query, {});
}

module.exports = { generateDeptReportPDF, generateStudentProfilePDF, generatePDF };
