// ─────────────────────────────────────────
//  generators/zipGenerator.js
//  Bundles multiple output files into a ZIP
// ─────────────────────────────────────────
const archiver = require('archiver');
const fs = require('fs');
const path = require('path');

const OUTPUT_DIR = process.env.OUTPUT_DIR || './outputs';

/**
 * Creates a ZIP archive from an array of file paths.
 * @param {string[]} filePaths - Array of file paths to include
 * @param {number}   timestamp - Unique timestamp for filename
 * @returns {Promise<string>}  - Path to the created ZIP file
 */
async function generateZIP(filePaths, timestamp) {
  const filename = `report_all_formats_${timestamp}.zip`;
  const zipPath = path.join(OUTPUT_DIR, filename);

  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', () => {
      console.log(`🗜️ ZIP generated: ${zipPath} (${archive.pointer()} bytes)`);
      resolve(zipPath);
    });
    archive.on('error', reject);

    archive.pipe(output);

    // Add each file to the archive
    filePaths.forEach(filePath => {
      if (fs.existsSync(filePath)) {
        archive.file(filePath, { name: path.basename(filePath) });
      }
    });

    // Add a README inside the ZIP
    const readmeContent = `Business Document Assistant - Report Bundle
============================================
Generated: ${new Date().toLocaleString()}

Files included:
${filePaths.map(f => `- ${path.basename(f)}`).join('\n')}

Generated by WhatsApp Business Document Assistant
`;
    archive.append(readmeContent, { name: 'README.txt' });

    archive.finalize();
  });
}

module.exports = { generateZIP };
